runtime: python27
api_version: 1
threadsafe: yes

handlers:

#- url: /client
#  static_dir: client

- url: .*  # This regex directs all routes to main.app
  script: main.app

#libraries:
#- name: jinja2
#  version: latest